version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./server
    environment:
      DATABASE_URL: postgres://postgres:Test@123@db:5432/todo
      ACCESS_TOKEN_SECRET: your-super-secret-jwt-key-here
      REFRESH_TOKEN_EXPIRES_SEC: 604800
      ACCESS_TOKEN_EXPIRES_IN: 15m
      NODE_ENV: production
      PORT: 4000
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
